"""empty message

Revision ID: eb55adc01b77
Revises: 
Create Date: 2022-07-11 04:16:41.429424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb55adc01b77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('home_team', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('away_team', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('home_team_win_odds', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('away_team_win_odds', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('draw_odds', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('game_date', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
